name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: foo
        run: |
          Get-ExecutionPolicy -List
          dir
        shell: powershell
