name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: bootstrap
        run: iwr -useb raw.githubusercontent.com/agate-pris/dotfiles/hello/.bin/bootstrap.ps1 | iex
        shell: powershell
